spring:
  application:
    name: demo-service
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  add-application-context-header: false
  context-path: /application
  info:
    git:
     mode: full

myapp:
  greeting: Hallo
