---
spring:
  application:
    name: demo-service
  jackson:
    serialization:
      write_dates_as_timestamps: false

demo:
  greeting: Hi (Default)

---
spring.profiles: dev
spring.profiles.include:
  - inmemory

demo:
  greeting: Hello (Dev)

---
spring.profiles: test
spring.profiles.include:
  - testdb

demo:
  greeting: Hello (test) New Feature

---
spring.profiles: prod
spring.profiles.include:
  - proddb

demo:
  greeting: Hello (Prod) New Feature
  ha: true